# Generated by Django 6.0.1 on 2026-01-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='jxclbx', max_length=64)),
                ('location', models.CharField(blank=True, default='Tianjin, China', max_length=128)),
                ('hobbies', models.CharField(blank=True, default='Aviation, Photography, Cycling', max_length=256)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('pinned_ids', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('camera', 'Camera'), ('lens', 'Lens')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='photos.siteprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('airline', models.CharField(db_index=True, max_length=256)),
                ('airport', models.CharField(db_index=True, max_length=256)),
                ('date', models.DateField(db_index=True)),
                ('sub_model', models.CharField(blank=True, default='', max_length=64)),
                ('remarks', models.TextField(blank=True, default='')),
                ('src', models.URLField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/')),
                ('featured', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(blank=True, limit_choices_to={'kind': 'camera'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_as_camera', to='photos.gearitem')),
                ('lens', models.ForeignKey(blank=True, limit_choices_to={'kind': 'lens'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_as_lens', to='photos.gearitem')),
            ],
            options={
                'indexes': [models.Index(fields=['-date'], name='idx_photo_date_desc'), models.Index(fields=['airport', '-date'], name='idx_airport_date_desc'), models.Index(fields=['airline', '-date'], name='idx_airline_date_desc'), models.Index(fields=['model', '-date'], name='idx_model_date_desc'), models.Index(fields=['-date', '-id'], name='idx_date_id_desc'), models.Index(fields=['reg', '-date'], name='idx_reg_date_desc'), models.Index(fields=['airport', 'airline', 'model', '-date'], name='idx_aam_date_desc')],
            },
        ),
    ]
