# Generated by Django 6.0.1 on 2026-02-19 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('airline', models.CharField(db_index=True, max_length=256)),
                ('airport', models.CharField(db_index=True, max_length=256)),
                ('date', models.DateField(db_index=True)),
                ('sub_model', models.CharField(blank=True, default='', max_length=64)),
                ('remarks', models.TextField(blank=True, default='')),
                ('src', models.URLField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pending/%Y/%m/')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('review_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(blank=True, limit_choices_to={'kind': 'camera'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_as_camera', to='photos.gearitem')),
                ('lens', models.ForeignKey(blank=True, limit_choices_to={'kind': 'lens'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_as_lens', to='photos.gearitem')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='idx_pending_status_time')],
            },
        ),
    ]
