# Generated by Django 6.0.1 on 2026-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_pendingphoto_user_photo_user_siteprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
