# Generated by Django 6.0.1 on 2026-02-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_siteprofile_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='display_name',
        ),
    ]
