# Generated by Django 6.0.1 on 2026-02-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_siteprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingphoto',
            name='image_lg',
            field=models.ImageField(blank=True, null=True, upload_to='pending/%Y/%m/lg/'),
        ),
        migrations.AddField(
            model_name='pendingphoto',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to='pending/%Y/%m/sm/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_lg',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/lg/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/sm/'),
        ),
    ]
