# Generated by Django 6.0.1 on 2026-02-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_pendingphoto_image_lg_pendingphoto_image_sm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingphoto',
            name='image_lg',
        ),
        migrations.RemoveField(
            model_name='pendingphoto',
            name='image_sm',
        ),
    ]
