# Generated by Django 6.0.1 on 2026-02-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_remove_pendingphoto_image_lg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingphoto',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to='pending/%Y/%m/sm/'),
        ),
    ]
