# Generated by Django 6.0.1 on 2026-03-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_pending_photo_add_image_sm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingphoto',
            name='is_bizjet',
            field=models.BooleanField(default=False, verbose_name='Business Jet'),
        ),
        migrations.AddField(
            model_name='pendingphoto',
            name='is_cargo',
            field=models.BooleanField(default=False, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='pendingphoto',
            name='is_helicopter',
            field=models.BooleanField(default=False, verbose_name='Helicopter'),
        ),
        migrations.AddField(
            model_name='pendingphoto',
            name='is_rare',
            field=models.BooleanField(default=False, verbose_name='Rare'),
        ),
        migrations.AddField(
            model_name='pendingphoto',
            name='is_special_livery',
            field=models.BooleanField(default=False, verbose_name='Special Livery'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_bizjet',
            field=models.BooleanField(default=False, verbose_name='Business Jet'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_cargo',
            field=models.BooleanField(default=False, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_helicopter',
            field=models.BooleanField(default=False, verbose_name='Helicopter'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_rare',
            field=models.BooleanField(default=False, verbose_name='Rare'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_special_livery',
            field=models.BooleanField(default=False, verbose_name='Special Livery'),
        ),
    ]
