# Generated by Django 6.0.1 on 2026-03-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_tempphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempPhoto',
        ),
    ]
