# Generated by Codex on 2026-03-13

from collections import Counter

from django.db import migrations, models


def seed_aircraft_submodels(apps, schema_editor):
    Photo = apps.get_model("photos", "Photo")
    AircraftSubModel = apps.get_model("photos", "AircraftSubModel")

    counts = Counter()
    for model, sub_model in Photo.objects.values_list("model", "sub_model").iterator():
        model = (model or "").strip()
        sub_model = (sub_model or "").strip()
        if model and sub_model:
            counts[(model, sub_model)] += 1

    AircraftSubModel.objects.bulk_create(
        [
            AircraftSubModel(model=model, sub_model=sub_model, usage_count=count)
            for (model, sub_model), count in sorted(counts.items())
        ]
    )


def clear_aircraft_submodels(apps, schema_editor):
    AircraftSubModel = apps.get_model("photos", "AircraftSubModel")
    AircraftSubModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0011_delete_tempphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftSubModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(db_index=True, max_length=64)),
                ("sub_model", models.CharField(max_length=64)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["model", "sub_model"],
            },
        ),
        migrations.AddConstraint(
            model_name="aircraftsubmodel",
            constraint=models.UniqueConstraint(
                fields=("model", "sub_model"),
                name="uniq_aircraft_model_sub_model",
            ),
        ),
        migrations.RunPython(seed_aircraft_submodels, clear_aircraft_submodels),
    ]
