# Generated by Django 6.0.1 on 2026-03-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_aircraftsubmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='show_perf_panel',
            field=models.BooleanField(default=False),
        ),
    ]
