# Generated by Django 6.0.1 on 2026-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_siteprofile_show_perf_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingphoto',
            name='approved_photo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
