# Generated by Django 6.0.1 on 2026-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_add_approved_photo_id_to_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pending_photo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
