# Generated by Django 6.0.1 on 2026-05-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_pending_photo_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingphoto',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
    ]
